Various improvements
yxdunc/lipl pull request #3
Opened 2019-12-22 22:29 UTC by IohannRabeson

2019-12-23 01:30 UTC, yxdunc requested changes
There is an unmatched bracket:
```
 src/widget_text_output.rs:22

unexpected close delimiter: `}`
```
Otherwise looks good to me.

2019-12-23 01:30 UTC, yxdunc commented on src/app.rs
> +        let regression: (f64, f64) = linear_regression_of(data).unwrap_or_default();
Oh, nice!

2019-12-23 15:33 UTC, IohannRabeson commented
Ho! Sorry for that! I will fix that as soon as possible later after work :)

Le dim. 22 déc. 2019 à 20:30, Robin <notifications@github.com> a écrit :

> *@yxdunc* requested changes on this pull request.
>
> There is an unmatched bracket:
>
>  src/widget_text_output.rs:22
>
> unexpected close delimiter: `}`
>
> Otherwise looks good to me.
> ------------------------------
>
> In src/app.rs
> <https://github.com/yxdunc/lipl/pull/3#discussion_r360740370>:
>
> > @@ -76,7 +76,7 @@ impl <'a> UI <'a> {
>          let min_value = data.iter().min_by(|x, y| x.1.partial_cmp(&y.1).unwrap()).unwrap().1 - 10.0;
>          let max_value = data.iter().max_by(|x, y| x.1.partial_cmp(&y.1).unwrap()).unwrap().1 + 10.0;
>          let command = self.command;
> -        let regression: (f64, f64) = linear_regression_of(data).or(Some((0.0, 0.0))).unwrap();
> +        let regression: (f64, f64) = linear_regression_of(data).unwrap_or_default();
>
> Oh, nice!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/yxdunc/lipl/pull/3?email_source=notifications&email_token=AAFHJDBADJ7Y4DD3JJ3TYVTQ2AICHA5CNFSM4J6NZBJ2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCQBBKWI#pullrequestreview-335680857>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAFHJDGYI7BJMMDROCBUNRDQ2AICHANCNFSM4J6NZBJQ>
> .
>

2019-12-26 17:53 UTC, yxdunc approved these changes

2019-12-27 23:55 UTC, merged